config/routes.rb
Rails.application.routes.draw do
	resources :rooms
	
  	root to: 'rooms#show'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	def show
	  	@messages = Message.all
	  	@message = Message.new
	end

	def create
		Message.create!(message_params)
	end

  	private

	def message_params
	  params.require(:message).permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= action_cable_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class=“message”>
  <p><%= message.content %></p>
</div>

app/views/rooms/show.html.erb
<h1>Chat room</h1>
  
<div id="messages">
  <%= render @messages %>
</div>

<!-- <form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form> -->

<%=form_for @message, url: rooms_path, remote: true, authenticity_token: true do |f|%>
  <%= f.label :your_message%>:
  <%= f.text_field :content, class: "form-control" %>

  <%#= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", data: {send: "message"}%>
<%end%>